name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homepage repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm install
          npm run build
        env:
          CI: true

      - name: Deploy to moonwx.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: moonwx/moonwx.github.io
          personal_token: ${{ secrets.GHP_KEY }}
          commit_message: ${{ github.event.head_commit.message }}
          publish_dir: ./dist

      - name: Add CNAME
        run: |
          cd .
          echo "moonwx.net" > CNAME
